import { ApprovedPlan, CompetitorBanner, CreativeCheck, GovernanceRule, Violation } from "./types";

export const seedRules: GovernanceRule[] = [
  {
    id: "r1", name: "Approved geo targeting only",
    description: "Campaigns may only target cities from the approved media plan.",
    category: "setup", platforms: ["Amazon", "Flipkart", "BlinkIt", "Zepto", "Instamart"],
    campaignTypes: ["Sponsored Products", "Sponsored Brand", "DSP"],
    severity: "critical", enabled: true, actionOnViolation: "review",
    config: { allowedCities: "Mumbai, Delhi, Bangalore, Hyderabad, Pune, Chennai" },
  },
  {
    id: "r2", name: "Frequency cap ceiling",
    description: "Frequency cap must not exceed 5 impressions / user / day.",
    category: "setup", platforms: ["Amazon", "Flipkart"], campaignTypes: ["DSP"],
    severity: "warning", enabled: true, actionOnViolation: "flag",
    config: { maxFrequency: "5 per user per day" },
  },
  {
    id: "r3", name: "Tracking parameter required",
    description: "All campaign URLs must include utm_source, utm_medium, utm_campaign.",
    category: "setup", platforms: ["Amazon", "Flipkart", "BlinkIt", "Zepto", "Instamart"],
    campaignTypes: ["Sponsored Products", "Sponsored Brand"],
    severity: "critical", enabled: true, actionOnViolation: "auto_pause",
    config: { requiredParams: "utm_source, utm_medium, utm_campaign" },
  },
  {
    id: "r4", name: "Allowed placements",
    description: "Only approved placements may be used.",
    category: "setup", platforms: ["Amazon"], campaignTypes: ["Sponsored Brand"],
    severity: "warning", enabled: true, actionOnViolation: "review",
    config: { allowedPlacements: "Search Top, Category, Brand Shelf" },
  },
  {
    id: "r5", name: "Naming convention",
    description: "Campaign names must follow Brand_Platform_Objective_YYYYMM.",
    category: "setup", platforms: ["Amazon", "Flipkart", "BlinkIt"], campaignTypes: ["All"],
    severity: "info", enabled: true, actionOnViolation: "flag",
    config: { pattern: "^[A-Z]+_[A-Z]+_[A-Z]+_\\d{6}$" },
  },
  {
    id: "r6", name: "Approved creative version",
    description: "Only the latest approved asset version may be served.",
    category: "creative", platforms: ["Amazon", "Flipkart"], campaignTypes: ["All"],
    severity: "critical", enabled: true, actionOnViolation: "review",
    config: { requireVersion: "Latest approved" },
  },
  {
    id: "r7", name: "Allowed landing page domains",
    description: "Landing pages must point to approved brand domains.",
    category: "creative", platforms: ["Amazon", "Flipkart", "BlinkIt", "Zepto", "Instamart"],
    campaignTypes: ["All"], severity: "critical", enabled: true, actionOnViolation: "auto_pause",
    config: { allowedDomains: "brand.com, amazon.in/brand, flipkart.com/brand" },
  },
  {
    id: "r8", name: "Required CTA",
    description: "Creative CTA must match the approved CTA in the media plan.",
    category: "creative", platforms: ["Amazon", "Flipkart"], campaignTypes: ["Sponsored Brand"],
    severity: "warning", enabled: true, actionOnViolation: "flag",
    config: { requiredCTA: "Shop Now / Buy Now" },
  },
];

export const seedPlans: ApprovedPlan[] = [
  {
    id: "p1", campaign: "BISCUIT_AMZN_AWARENESS_202607", platform: "Amazon",
    objective: "Awareness", audience: "Snack Buyers 25-45",
    geo: ["Mumbai", "Delhi", "Bangalore"], frequencyCap: "5/day",
    placements: ["Search Top", "Category"], trackingParams: "utm_source=amazon&utm_medium=cpc&utm_campaign=awareness",
    dailyBudget: 12000, startDate: "2026-06-01", endDate: "2026-07-31",
    approvedBy: "M. Sharma", status: "approved",
  },
  {
    id: "p2", campaign: "BISCUIT_FLPK_CONSIDERATION_202607", platform: "Flipkart",
    objective: "Consideration", audience: "Repeat shoppers",
    geo: ["Mumbai", "Pune", "Hyderabad"], frequencyCap: "4/day",
    placements: ["Brand Shelf", "Home Carousel"], trackingParams: "utm_source=flipkart&utm_medium=cpc&utm_campaign=consider",
    dailyBudget: 9500, startDate: "2026-06-15", endDate: "2026-07-31",
    approvedBy: "R. Iyer", status: "approved",
  },
  {
    id: "p3", campaign: "CREATINE_BLNK_CONVERSION_202607", platform: "BlinkIt",
    objective: "Conversion", audience: "Fitness 18-35",
    geo: ["Bangalore", "Hyderabad", "Mumbai"], frequencyCap: "6/day",
    placements: ["Category", "Search Top"], trackingParams: "utm_source=blinkit&utm_medium=cpc&utm_campaign=convert",
    dailyBudget: 8000, startDate: "2026-06-10", endDate: "2026-07-15",
    approvedBy: "S. Kapoor", status: "approved",
  },
  {
    id: "p4", campaign: "COOKIES_ZEPTO_CONVERSION_202607", platform: "Zepto",
    objective: "Conversion", audience: "Q-Commerce repeat",
    geo: ["Mumbai", "Delhi"], frequencyCap: "5/day",
    placements: ["Category"], trackingParams: "utm_source=zepto&utm_medium=cpc&utm_campaign=convert",
    dailyBudget: 6000, startDate: "2026-06-20", endDate: "2026-07-20",
    approvedBy: "M. Sharma", status: "approved",
  },
];

export const seedViolations: Violation[] = [
  {
    id: "v1", campaign: "BISCUIT_AMZN_AWARENESS_202607", platform: "Amazon",
    rule: "Approved geo targeting only", field: "Geo",
    approved: "Mumbai, Delhi, Bangalore", live: "Mumbai, Delhi, Bangalore, Kolkata, Ahmedabad",
    severity: "critical", status: "open", detectedAt: "2026-06-29 09:14", impact: "spend_at_risk",
  },
  {
    id: "v2", campaign: "BISCUIT_FLPK_CONSIDERATION_202607", platform: "Flipkart",
    rule: "Tracking parameter required", field: "Tracking params",
    approved: "utm_source, utm_medium, utm_campaign", live: "utm_source, utm_medium (missing utm_campaign)",
    severity: "critical", status: "open", detectedAt: "2026-06-30 04:02", impact: "policy",
  },
  {
    id: "v3", campaign: "CREATINE_BLNK_CONVERSION_202607", platform: "BlinkIt",
    rule: "Frequency cap ceiling", field: "Frequency cap",
    approved: "6/day", live: "9/day", severity: "warning", status: "open",
    detectedAt: "2026-06-30 03:45", impact: "spend_at_risk",
  },
  {
    id: "v4", campaign: "COOKIES_ZEPTO_CONVERSION_202607", platform: "Zepto",
    rule: "Allowed placements", field: "Placements",
    approved: "Category", live: "Category, Home Carousel",
    severity: "warning", status: "pause_requested", detectedAt: "2026-06-29 18:21", impact: "policy",
  },
  {
    id: "v5", campaign: "biscuit_amzn_summer", platform: "Amazon",
    rule: "Naming convention", field: "Campaign name",
    approved: "BRAND_PLATFORM_OBJECTIVE_YYYYMM", live: "biscuit_amzn_summer",
    severity: "info", status: "open", detectedAt: "2026-06-28 11:00", impact: "policy",
  },
  {
    id: "v6", campaign: "BISCUIT_AMZN_AWARENESS_202607", platform: "Amazon",
    rule: "Approved creative version", field: "Asset version",
    approved: "v3.2 (approved 2026-06-15)", live: "v2.1",
    severity: "critical", status: "fix_requested", detectedAt: "2026-06-27 14:30", impact: "brand_risk",
  },
  {
    id: "v7", campaign: "BISCUIT_FLPK_CONSIDERATION_202607", platform: "Flipkart",
    rule: "Allowed landing page domains", field: "Landing page",
    approved: "flipkart.com/brand", live: "flipkart.com/promo-2024-old",
    severity: "critical", status: "waived", detectedAt: "2026-06-26 10:15", impact: "brand_risk",
    note: "Temporary landing page approved by brand team for 7 days.",
  },
  {
    id: "v8", campaign: "CREATINE_BLNK_CONVERSION_202607", platform: "BlinkIt",
    rule: "Required CTA", field: "CTA",
    approved: "Shop Now", live: "Learn More",
    severity: "warning", status: "open", detectedAt: "2026-06-30 01:10", impact: "brand_risk",
  },
  {
    id: "v9", campaign: "COOKIES_ZEPTO_CONVERSION_202607", platform: "Zepto",
    rule: "Approved geo targeting only", field: "Geo",
    approved: "Mumbai, Delhi", live: "Mumbai, Delhi, Jaipur",
    severity: "critical", status: "open", detectedAt: "2026-06-29 22:00", impact: "spend_at_risk",
  },
  {
    id: "v10", campaign: "BISCUIT_AMZN_AWARENESS_202607", platform: "Amazon",
    rule: "Objective mismatch", field: "Objective",
    approved: "Awareness", live: "Conversion",
    severity: "warning", status: "open", detectedAt: "2026-06-28 08:00", impact: "policy",
  },
];

const platformPass = [
  { label: "Aspect ratio", required: "16:9", actual: "16:9", pass: true, critical: true },
  { label: "Min resolution", required: "1920×1080", actual: "1920×1080", pass: true, critical: true },
  { label: "Max file size", required: "≤ 500 KB", actual: "412 KB", pass: true },
  { label: "Safe zone", required: "80 px margin", actual: "82 px", pass: true },
  { label: "Max text coverage", required: "≤ 20%", actual: "17%", pass: true, critical: true },
  { label: "File type", required: "JPG / PNG", actual: "JPG", pass: true },
];

const brandPass = [
  { label: "Logo present", required: "Top-left, ≥ 64 px", actual: "Top-left, 72 px", pass: true, critical: true },
  { label: "Product name visible", required: "Legible ≥ 24 pt", actual: "28 pt", pass: true, critical: true },
  { label: "Mandatory disclaimer", required: "FSSAI + Net wt.", actual: "Both present", pass: true },
  { label: "Approved colour palette", required: "Brand red #C8102E", actual: "#C8102E", pass: true },
  { label: "Approved font", required: "Britannia Sans", actual: "Britannia Sans", pass: true },
  { label: "Price/offer legibility", required: "≥ 32 pt bold", actual: "36 pt bold", pass: true },
];

export const seedCreatives: CreativeCheck[] = [
  {
    id: "c1", publisher: "Amazon", sku: "BISC-001", productName: "Cream Biscuits 250g",
    approvedAssetVersion: "v3.2", servedAssetVersion: "v3.2",
    approvedLandingPage: "amazon.in/brand/bisc-001", servedLandingPage: "amazon.in/brand/bisc-001",
    approvedCTA: "Shop Now", servedCTA: "Shop Now",
    status: "ok", mismatchTypes: [],
    surface: "Homepage Hero", slot: "Slot #1", state: "active",
    thumbColor: "#C8102E", verdict: "pass",
    platformChecks: platformPass, brandChecks: brandPass,
  },
  {
    id: "c2", publisher: "Amazon", sku: "BISC-002", productName: "Choco Cookies 200g",
    approvedAssetVersion: "v3.2", servedAssetVersion: "v2.1",
    approvedLandingPage: "amazon.in/brand/bisc-002", servedLandingPage: "amazon.in/brand/bisc-002",
    approvedCTA: "Shop Now", servedCTA: "Shop Now",
    status: "mismatch", mismatchTypes: ["asset"],
    surface: "Category Page Banner", slot: "Position 2", state: "active",
    thumbColor: "#5B3A1F", verdict: "blocked",
    platformChecks: [
      ...platformPass.slice(0, 3),
      { label: "Safe zone", required: "80 px margin", actual: "48 px", pass: false, critical: true },
      { label: "Max text coverage", required: "≤ 20%", actual: "31%", pass: false, critical: true },
      platformPass[5],
    ],
    brandChecks: [
      brandPass[0],
      { label: "Product name visible", required: "Legible ≥ 24 pt", actual: "18 pt (truncated)", pass: false, critical: true },
      ...brandPass.slice(2),
    ],
  },
  {
    id: "c3", publisher: "Flipkart", sku: "BISC-002", productName: "Choco Cookies 200g",
    approvedAssetVersion: "v3.2", servedAssetVersion: "v3.2",
    approvedLandingPage: "flipkart.com/brand/cookies", servedLandingPage: "flipkart.com/promo-2024-old",
    approvedCTA: "Buy Now", servedCTA: "Buy Now",
    status: "mismatch", mismatchTypes: ["landing_page"],
    surface: "Featured Banner", slot: "Home Rail A", state: "active",
    thumbColor: "#2874F0", verdict: "warning",
    platformChecks: platformPass,
    brandChecks: [
      { label: "Logo present", required: "Top-left, ≥ 64 px", actual: "Top-left, 58 px", pass: false },
      ...brandPass.slice(1),
    ],
  },
  {
    id: "c4", publisher: "Flipkart", sku: "BISC-003", productName: "Glucose Biscuits 120g",
    approvedAssetVersion: "v1.4", servedAssetVersion: "v1.2",
    approvedLandingPage: "flipkart.com/brand/glucose", servedLandingPage: "flipkart.com/brand/glucose",
    approvedCTA: "Shop Now", servedCTA: "Learn More",
    status: "mismatch", mismatchTypes: ["asset", "cta"],
    surface: "Category Top Slot", slot: "Snacks · Slot #1", state: "active",
    thumbColor: "#F4B400", verdict: "blocked",
    platformChecks: platformPass,
    brandChecks: [
      ...brandPass.slice(0, 2),
      { label: "Mandatory disclaimer", required: "FSSAI + Net wt.", actual: "FSSAI missing", pass: false, critical: true },
      ...brandPass.slice(3),
    ],
  },
  {
    id: "c5", publisher: "BlinkIt", sku: "BISC-004", productName: "Marie Gold 200g",
    approvedAssetVersion: "v1.4", servedAssetVersion: "—",
    approvedLandingPage: "blinkit.com/brand/marie", servedLandingPage: "—",
    approvedCTA: "Shop Now", servedCTA: "—",
    status: "missing", mismatchTypes: ["asset", "landing_page", "cta"],
    surface: "Homepage Carousel", slot: "Slot #3", state: "active",
    thumbColor: "#F7C548", verdict: "blocked",
    platformChecks: [
      { label: "Aspect ratio", required: "1:1", actual: "—", pass: false, critical: true },
      { label: "Min resolution", required: "1080×1080", actual: "—", pass: false, critical: true },
      ...platformPass.slice(2),
    ],
    brandChecks: brandPass,
  },
  {
    id: "c6", publisher: "Zepto", sku: "BISC-001", productName: "Cream Biscuits 250g",
    approvedAssetVersion: "v3.2", servedAssetVersion: "v3.2",
    approvedLandingPage: "zepto.com/brand/biscuits", servedLandingPage: "zepto.com/brand/biscuits",
    approvedCTA: "Buy Now", servedCTA: "Order Now",
    status: "mismatch", mismatchTypes: ["cta"],
    surface: "Category Page Banner", slot: "Position 1", state: "active",
    thumbColor: "#7C3AED", verdict: "warning",
    platformChecks: platformPass,
    brandChecks: brandPass,
  },
  {
    id: "c7", publisher: "Instamart", sku: "BISC-002", productName: "Choco Cookies 200g",
    approvedAssetVersion: "v3.2", servedAssetVersion: "v3.2",
    approvedLandingPage: "instamart.com/brand/cookies", servedLandingPage: "instamart.com/brand/cookies",
    approvedCTA: "Shop Now", servedCTA: "Shop Now",
    status: "ok", mismatchTypes: [],
    surface: "Featured Banner", slot: "Category · Snacks", state: "active",
    thumbColor: "#F97316", verdict: "pass",
    platformChecks: platformPass, brandChecks: brandPass,
  },
  // preflight creatives
  {
    id: "c8", publisher: "Amazon", sku: "BISC-005", productName: "Bourbon Cream 150g",
    approvedAssetVersion: "v4.0", servedAssetVersion: "v4.0-draft",
    approvedLandingPage: "amazon.in/brand/bourbon", servedLandingPage: "amazon.in/brand/bourbon",
    approvedCTA: "Shop Now", servedCTA: "Shop Now",
    status: "ok", mismatchTypes: [],
    surface: "Homepage Hero", slot: "Slot #1 (Jul launch)", state: "preflight",
    scheduledGoLive: "2026-07-05",
    thumbColor: "#8B4513", verdict: "pass",
    platformChecks: platformPass, brandChecks: brandPass,
  },
  {
    id: "c9", publisher: "Flipkart", sku: "BISC-006", productName: "Digestive 120g",
    approvedAssetVersion: "v2.0", servedAssetVersion: "v2.0-draft",
    approvedLandingPage: "flipkart.com/brand/digestive", servedLandingPage: "flipkart.com/brand/digestive",
    approvedCTA: "Buy Now", servedCTA: "Buy Now",
    status: "ok", mismatchTypes: [],
    surface: "Category Page Banner", slot: "Position 1", state: "preflight",
    scheduledGoLive: "2026-07-03",
    thumbColor: "#A0522D", verdict: "warning",
    platformChecks: [
      ...platformPass.slice(0, 4),
      { label: "Max text coverage", required: "≤ 20%", actual: "24%", pass: false },
      platformPass[5],
    ],
    brandChecks: brandPass,
  },
  {
    id: "c10", publisher: "BlinkIt", sku: "BISC-007", productName: "Hide & Seek Choco 120g",
    approvedAssetVersion: "v1.0", servedAssetVersion: "v1.0-draft",
    approvedLandingPage: "blinkit.com/brand/hns", servedLandingPage: "blinkit.com/brand/hns",
    approvedCTA: "Order Now", servedCTA: "Order Now",
    status: "ok", mismatchTypes: [],
    surface: "Featured Banner", slot: "Home Rail B", state: "preflight",
    scheduledGoLive: "2026-07-02",
    thumbColor: "#1F2937", verdict: "blocked",
    platformChecks: platformPass,
    brandChecks: [
      { label: "Logo present", required: "Top-left, ≥ 64 px", actual: "Missing", pass: false, critical: true },
      { label: "Product name visible", required: "Legible ≥ 24 pt", actual: "20 pt", pass: false, critical: true },
      ...brandPass.slice(2),
    ],
  },
  {
    id: "c11", publisher: "Zepto", sku: "BISC-008", productName: "Anmol Marie 250g",
    approvedAssetVersion: "v1.1", servedAssetVersion: "v1.1-draft",
    approvedLandingPage: "zepto.com/brand/anmol", servedLandingPage: "zepto.com/brand/anmol",
    approvedCTA: "Buy Now", servedCTA: "Buy Now",
    status: "ok", mismatchTypes: [],
    surface: "Homepage Carousel", slot: "Slot #2", state: "preflight",
    scheduledGoLive: "2026-07-07",
    thumbColor: "#6D28D9", verdict: "pass",
    platformChecks: platformPass, brandChecks: brandPass,
  },
  {
    id: "c12", publisher: "Instamart", sku: "BISC-009", productName: "Sunfeast Dark Fantasy 100g",
    approvedAssetVersion: "v2.3", servedAssetVersion: "v2.3-draft",
    approvedLandingPage: "instamart.com/brand/darkfantasy", servedLandingPage: "instamart.com/brand/darkfantasy",
    approvedCTA: "Shop Now", servedCTA: "Shop Now",
    status: "ok", mismatchTypes: [],
    surface: "Category Top Slot", slot: "Snacks · Slot #2", state: "preflight",
    scheduledGoLive: "2026-07-04",
    thumbColor: "#111827", verdict: "warning",
    platformChecks: [
      ...platformPass.slice(0, 2),
      { label: "Max file size", required: "≤ 500 KB", actual: "612 KB", pass: false },
      ...platformPass.slice(3),
    ],
    brandChecks: brandPass,
  },
];

export const seedCompetitorBanners: CompetitorBanner[] = [
  {
    id: "cb1", competitor: "Parle", competitorBrand: "Parle-G", platform: "BlinkIt",
    surface: "Homepage Hero", slot: "Slot #1", thumbColor: "#FDB913",
    headline: "Parle-G ₹10 off · Every Household",
    shareOfVoice: 42, estSpendIndex: 118, daysLive: 12,
    ownSlot: "Slot #3", ownShareOfVoice: 18,
    positionalVerdict: "behind", shareVerdict: "behind",
  },
  {
    id: "cb2", competitor: "ITC", competitorBrand: "Sunfeast", platform: "Zepto",
    surface: "Homepage Hero", slot: "Slot #2", thumbColor: "#DC2626",
    headline: "Sunfeast Dark Fantasy · Buy 2 Get 1",
    shareOfVoice: 28, estSpendIndex: 92, daysLive: 8,
    ownSlot: "Slot #1", ownShareOfVoice: 46,
    positionalVerdict: "beating", shareVerdict: "beating",
  },
  {
    id: "cb3", competitor: "Unibic", competitorBrand: "Unibic Cookies", platform: "Instamart",
    surface: "Category Page Banner", slot: "Position 1", thumbColor: "#B45309",
    headline: "Cookies Fest · Flat 25% off",
    shareOfVoice: 35, estSpendIndex: 84, daysLive: 6,
    ownSlot: "Position 3", ownShareOfVoice: 22,
    positionalVerdict: "behind", shareVerdict: "behind",
  },
  {
    id: "cb4", competitor: "Parle", competitorBrand: "Hide & Seek", platform: "BlinkIt",
    surface: "Category Page Banner", slot: "Position 2", thumbColor: "#1F2937",
    headline: "Hide & Seek · New Milano",
    shareOfVoice: 22, estSpendIndex: 76, daysLive: 4,
    ownSlot: "Position 1", ownShareOfVoice: 38,
    positionalVerdict: "beating", shareVerdict: "beating",
  },
  {
    id: "cb5", competitor: "ITC", competitorBrand: "Sunfeast Marie", platform: "Amazon",
    surface: "Featured Banner", slot: "Home Rail A", thumbColor: "#DC2626",
    headline: "Marie Light · Family Pack",
    shareOfVoice: 31, estSpendIndex: 88, daysLive: 10,
    ownSlot: undefined, ownShareOfVoice: 0,
    positionalVerdict: "absent", shareVerdict: "absent",
  },
  {
    id: "cb6", competitor: "Anmol", competitorBrand: "Anmol Glucose", platform: "Flipkart",
    surface: "Featured Banner", slot: "Home Rail B", thumbColor: "#059669",
    headline: "Glucose Boost · ₹5 off",
    shareOfVoice: 18, estSpendIndex: 54, daysLive: 5,
    ownSlot: "Home Rail A", ownShareOfVoice: 32,
    positionalVerdict: "beating", shareVerdict: "beating",
  },
  {
    id: "cb7", competitor: "Parle", competitorBrand: "Monaco", platform: "Zepto",
    surface: "Category Top Slot", slot: "Snacks · Slot #1", thumbColor: "#F59E0B",
    headline: "Monaco · Perfect Snack Time",
    shareOfVoice: 40, estSpendIndex: 96, daysLive: 9,
    ownSlot: "Snacks · Slot #2", ownShareOfVoice: 26,
    positionalVerdict: "behind", shareVerdict: "behind",
  },
  {
    id: "cb8", competitor: "ITC", competitorBrand: "Bounce", platform: "Instamart",
    surface: "Homepage Carousel", slot: "Slot #2", thumbColor: "#7C2D12",
    headline: "Bounce Cream · New Flavours",
    shareOfVoice: 24, estSpendIndex: 68, daysLive: 7,
    ownSlot: undefined, ownShareOfVoice: 0,
    positionalVerdict: "absent", shareVerdict: "absent",
  },
  {
    id: "cb9", competitor: "Unibic", competitorBrand: "Unibic Choco", platform: "BlinkIt",
    surface: "PDP Cross-sell", slot: "Related Items", thumbColor: "#78350F",
    headline: "You may also like · Unibic",
    shareOfVoice: 15, estSpendIndex: 40, daysLive: 3,
    ownSlot: "Related Items", ownShareOfVoice: 20,
    positionalVerdict: "beating", shareVerdict: "beating",
  },
  {
    id: "cb10", competitor: "Parle", competitorBrand: "Krackjack", platform: "Amazon",
    surface: "Search Top", slot: "Position 1", thumbColor: "#EA580C",
    headline: "Krackjack · Sweet & Salty",
    shareOfVoice: 33, estSpendIndex: 90, daysLive: 11,
    ownSlot: "Position 2", ownShareOfVoice: 27,
    positionalVerdict: "behind", shareVerdict: "behind",
  },
];
